cache:
  key: ${CI_COMMIT_BRANCH}
  paths:
    - .npm/
    - .next/cache/

stages:
  - build
  - deploy
  - docker
  - publish
  - notify

include:
  - project: "utils/shared-ci"
    file: "docker-build.yml"
  - project: "utils/shared-ci"
    file: "update-cluster.yml"

variables:
  NAMESPACE: ix-medical-app-frontend
  NAMESPACE_DEV: $NAMESPACE-dev
  CHART: medical-app-frontend-ix-chart
  CHART_DEV: medical-app-frontend-dev-ix-chart
  DOCKER_FILE: ./Dockerfile
  DOCKER: registry.exz-vps.ru/alexioll-group/wedding-invite/frontend

build-frontend-docker-image:
  extends: .build-docker
  needs: []
  variables:
    DOCKER: registry.exz-vps.ru/alexioll-group/wedding-invite/frontend
    DOCKER_FILE: ./frontend/Dockerfile
  rules:
    - if: $IS_MAIN
      when: always
    - if: $IS_DEV
      when: never

build-backend-docker-image:
  extends: .build-docker
  needs: []
  variables:
    DOCKER: registry.exz-vps.ru/alexioll-group/wedding-invite/backend
    DOCKER_FILE: ./backend/Dockerfile
  rules:
    - if: $IS_MAIN
      when: always
    - if: $IS_DEV
      when: never

update-cluster-app:
  stage: publish
  image: docker:24.0.7
  services:
    - docker:dind
  tags:
    - truenas
  needs:
    - job: build-backend-docker-image
    - job: build-frontend-docker-image
  # before_script:
    # - docker login -u bustexz -p $DOCKER_PASSWORD
  script:
    - docker compose -f docker-compose.prod.yml pull
    - docker compose -f docker-compose.prod.yml up -d
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
