services:
  # База данных
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wedding_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Бэкенд
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/wedding_db
      - ADMIN_PIN=${ADMIN_PIN}
      - IS_DOCKER=true
    depends_on:
      - db
  # Фронтенд
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - VITE_API_URL=http://localhost:3000

volumes:
  db_data:
